# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed3ed75fda32d9cb6fa32b8ef07758cb3088cf393a4c380c9899af318a873e5f9a20595a06a31701688b991a4fb9113376a89502fc5ff6df17d3dcbdee2dd995

test:
  secret_key_base: 15c2bcd132baf5cca2852f2afc70c97c2946b6a094e3e59a985a12ce2a63775f1728b051f185dd8a0bf6c2d5702f7bd8f0d99a74d51c7a8833b09f902c8c0a2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
